#!/bin/sh
#
# Copyright (C) 2010-2012 Ian Moore <imooreyahoo@gmail.com>
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SHELL_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-shell.conf"

if [ -e "${SHELL_SITE_CONF}" ]; then
    rm -f ${SHELL_SITE_CONF}
fi

if [ "$(omv_config_get "//system/shell/enable")" != "1" ]; then
    exit 0
fi

cat <<EOF > "${SHELL_SITE_CONF}"
server {
    location /shell/ {
        proxy_pass http://localhost:4200/;
    }
}
EOF

exit 0
