#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


OMV_NGINX_WEBGUI_CONFIG_DIR=${OMV_NGINX_WEBGUI_CONFIG_DIR:-"/etc/nginx/openmediavault-webgui.d"}

OMV_SHELL_CONFIG_DIR=${OMV_SHELL_CONFIG_DIR:-"/etc/shellinabox"}
OMV_SHELL_DEFAULT=${OMV_SHELL_DEFAULT:-"/etc/default/shellinabox"}
OMV_SHELL_NGINX=${OMV_SHELL_NGINX:-"${OMV_NGINX_WEBGUI_CONFIG_DIR}/openmediavault-shellinabox.conf"}
OMV_SHELL_TERMCSS=${OMV_SHELL_TERMCSS:-"${OMV_SHELL_CONFIG_DIR}/termstyle.css"}

if [ -e "${OMV_SHELL_NGINX}" ]; then
    rm -f ${OMV_SHELL_NGINX}
fi

if [ "$(omv_config_get "//services/shellinabox/enable")" != "1" ]; then
    exit 0
fi

xmlstarlet sel -t -m "//services/shellinabox" \
  -o "SHELLINABOX_DAEMON_START=1" -n \
  -o "SHELLINABOX_PORT=4200" -n \
  -o "SHELLINABOX_ARGS=\"--disable-ssl-menu --service=/:SSH " \
  -i "enablebeep[. = '0']" -o "--no-beep " -b \
  -i "string-length(linkify) > 0" -v "concat('--linkify=', linkify)" -b \
  -i "enabletermsettings[. = '1']" -o " --css=${OMV_SHELL_TERMCSS}" -b \
  -o "\"" ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_SHELL_DEFAULT}

cat <<EOF > "${OMV_SHELL_NGINX}"
location /shellinabox {
    return 301 https://\$host:4200/;
}
EOF

chmod 644 ${OMV_SHELL_NGINX}

xmlstarlet sel -t -m "//services/shellinabox" \
  -o "#vt100 #console, #vt100 #alt_console, #vt100 #cursor, #vt100 #lineheight, #vt100 .hidden pre {" -n \
  -i "string-length(fontfamily) > 0" -v "concat('    font-family: \"', fontfamily, '\";')" -n -b \
  -i "fontsize > 0" -v "concat('    font-size: ', fontsize, 'px;')" -n -b \
  -o "}" ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_SHELL_TERMCSS}

systemctl reload nginx.service

