#!/bin/sh
#
#Copyright (c) 2013-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ]; then
            systemctl stop shellinabox.service
            systemctl disable shellinabox.service
        fi
        
        SERVICE_XPATH_NAME="shellinabox"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
        
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Initialize configuration"
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "linkify" "none"
            omv_config_add_element "${SERVICE_XPATH}" "enablebeep" "0"
            omv_config_add_element "${SERVICE_XPATH}" "enabletermsettings" "0"
            omv_config_add_element "${SERVICE_XPATH}" "fontfamily" "Courier New"
            omv_config_add_element "${SERVICE_XPATH}" "fontsize" "14"
        fi

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
