#!/bin/sh
#
# @license http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if ! omv_config_exists "/config/system/shell"; then
            echo "Initialize configuration"
            object="<enable>0</enable>"
            object="${object}<linkify>none</linkify>"
            object="${object}<enablebeep>0</enablebeep>"
            object="${object}<enabletermsettings>0</enabletermsettings>"
            object="${object}<fontfamily>Courier New</fontfamily>"
            object="${object}<fontsize>14</fontsize>"
            omv_config_add_element "/config/system" "shell" "${object}" true
        fi

        if [ -x "/etc/init.d/shellinabox" ]; then
            update-rc.d shellinabox start 30 2 3 4 5 . stop 01 0 1 6 . > /dev/null
        fi

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
